"""
Zemberek: Adding Dictionary Item Example
Java Code Example: https://bit.ly/2qTlmXb
"""

from os.path import join

from jpype import JClass, JString, getDefaultJVMPath, shutdownJVM, startJVM

if __name__ == '__main__':

    ZEMBEREK_PATH: str = join('..', '..', 'bin', 'zemberek-full.jar')

    startJVM(
        getDefaultJVMPath(),
        '-ea',
        f'-Djava.class.path={ZEMBEREK_PATH}',
        convertStrings=False
    )

    TurkishMorphology: JClass = JClass('zemberek.morphology.TurkishMorphology')
    DictionaryItem: JClass = JClass(
        'zemberek.morphology.lexicon.DictionaryItem'
    )
    RootAttribute: JClass = JClass('zemberek.core.turkish.RootAttribute')
    PrimaryPos: JClass = JClass('zemberek.core.turkish.PrimaryPos')
    SecondaryPos: JClass = JClass('zemberek.core.turkish.SecondaryPos')
    WordAnalysis: JClass = JClass('zemberek.morphology.analysis.WordAnalysis')

    morphology: TurkishMorphology = TurkishMorphology.createWithDefaults()

    def test(inp: str, new_item: DictionaryItem):
        print(f'Parses for {inp} before adding {new_item}')
        before: WordAnalysis = morphology.analyze(JString(inp))
        print_results(before)
        morphology.invalidateCache()
        morphology.getMorphotactics().getStemTransitions().addDictionaryItem(
            new_item
        )
        after: WordAnalysis = morphology.analyze(inp)
        print(f'Parses for {inp} after adding {new_item}')
        print_results(after)

    def print_results(results: WordAnalysis):
        if results.analysisCount() == 0:
            print('No Analysis')
        for i, result in enumerate(results, start=1):
            rstr: str = str(result.formatLong())
            if result.getDictionaryItem().attributes.contains(
                RootAttribute.Runtime
            ):
                rstr += ' (Generated by UnidentifiedTokenParser)\n'
            print(f'{i} - {rstr}')

    print('\nProper Noun Test - 1:\n')
    test(
        'Meydan\'a',
        DictionaryItem(
            JString('Meydan'),
            JString('meydan'),
            JString('meydan'),
            PrimaryPos.Noun,
            SecondaryPos.ProperNoun
        )
    )

    print('\nProper Noun Test - 2:\n')
    test(
        'Meeeydan\'a',
        DictionaryItem(
            JString('Meeeydan'),
            JString('meeeydan'),
            JString('meeeydan'),
            PrimaryPos.Noun,
            SecondaryPos.ProperNoun
        )
    )

    print('\nVerb Test:\n')
    test(
        'tweetleyeyazdım',
        DictionaryItem(
            JString('tweetlemek'),
            JString('tweetle'),
            JString('tivitle'),
            PrimaryPos.Verb,
            SecondaryPos.None_
        )
    )

    shutdownJVM()
